/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as DocumentsVariablesRouteImport } from './routes/documents.variables'
import { Route as DocumentsTemplateIdRouteImport } from './routes/documents.$templateId'

const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsVariablesRoute = DocumentsVariablesRouteImport.update({
  id: '/documents/variables',
  path: '/documents/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsTemplateIdRoute = DocumentsTemplateIdRouteImport.update({
  id: '/documents/$templateId',
  path: '/documents/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/employers': typeof EmployersRoute
  '/documents/$templateId': typeof DocumentsTemplateIdRoute
  '/documents/variables': typeof DocumentsVariablesRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/employers': typeof EmployersRoute
  '/documents/$templateId': typeof DocumentsTemplateIdRoute
  '/documents/variables': typeof DocumentsVariablesRoute
  '/documents': typeof DocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/employers': typeof EmployersRoute
  '/documents/$templateId': typeof DocumentsTemplateIdRoute
  '/documents/variables': typeof DocumentsVariablesRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencies'
    | '/employers'
    | '/documents/$templateId'
    | '/documents/variables'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencies'
    | '/employers'
    | '/documents/$templateId'
    | '/documents/variables'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/agencies'
    | '/employers'
    | '/documents/$templateId'
    | '/documents/variables'
    | '/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenciesRoute: typeof AgenciesRoute
  EmployersRoute: typeof EmployersRoute
  DocumentsTemplateIdRoute: typeof DocumentsTemplateIdRoute
  DocumentsVariablesRoute: typeof DocumentsVariablesRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/variables': {
      id: '/documents/variables'
      path: '/documents/variables'
      fullPath: '/documents/variables'
      preLoaderRoute: typeof DocumentsVariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$templateId': {
      id: '/documents/$templateId'
      path: '/documents/$templateId'
      fullPath: '/documents/$templateId'
      preLoaderRoute: typeof DocumentsTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenciesRoute: AgenciesRoute,
  EmployersRoute: EmployersRoute,
  DocumentsTemplateIdRoute: DocumentsTemplateIdRoute,
  DocumentsVariablesRoute: DocumentsVariablesRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
